### ISSUE TITLE
home/news: Responsive behaviour

### ISSUE THREAD

**Issue by darrenbarklie** [darrenbarklie/maccop#1]
![image](https://user-images.githubusercontent.com/3026261/33142186-7c868912-cfad-11e7-82f0-9c94226dce74.png)
I can understand what you did here, but I don't think it looks good.  Can you use flexbox and set `justify-content` parameter or `space-around` so that the last item is the same width, but centrally aligned?

**Comment by darrenbarklie** [comment]
By the way, last item = width 100% is fine for the Journals section, as it is text only.

**Comment by thanhthao993** [comment]
Fixed! Please check it. Thanks men! :)

**Comment by darrenbarklie** [comment]
Fixed.  Thanks!
