### ISSUE TITLE
Sponsor & Donation responsive tables

### ISSUE THREAD

**Issue by darrenbarklie** [darrenbarklie/maccop#13]
![image](https://user-images.githubusercontent.com/3026261/33571777-01a7788e-d929-11e7-9d21-b8309dd03564.png)
We need a solution for this: on mobile you can't view the donation values, which is critical information.

Options:
1. Vertical scroll on the element
2. With a @mediaquery, swap the whole table asset for a simple plain-text list, e.g.:

- **Sponsor a Child in Nursey & Primary**
- 2074KSH per month
- 20USD per month
- 15GBP per month
- 18 EUR per month
- **Sponsor a Child in Secondary**
- 2074KSH per month
- 20USD per month
- 15GBP per month
- 18 EUR per month

Check any tables across the site have a solution in place.  Thanks!

**Comment by thanhthao993** [comment]
I did choose option 1: Vertical scroll on the element

**Comment by darrenbarklie** [comment]
Yeah, noticed this.  Great job - thanks!
