### ISSUE TITLE
Navigation tablet

### ISSUE THREAD

**Issue by darrenbarklie** [darrenbarklie/maccop#17]
![image](https://user-images.githubusercontent.com/3026261/33713056-8efb250e-db41-11e7-9eda-390d82dc3077.png)
Need a specific `@mediaquery` to help the navigation here.  Try to vertically align the text in the middle (red dotted line in screenshot).

**Comment by darrenbarklie** [comment]
And ensure the grey divider lines stretch 100% height.  :)

**Comment by thanhthao993** [comment]
I made it like this. Do you have any solutions with this navigation to make it smaller?
![2017-12-07_21-37-20](https://user-images.githubusercontent.com/10804177/33720641-1f32cd0c-db97-11e7-8474-9e6a7e67c7e4.png)

**Comment by darrenbarklie** [comment]
I think that this is fine, I added a little extra padding to the `.banner` to compensate the extra height.  Closing.
