### ISSUE TITLE
global: Footer fixes

### ISSUE THREAD

**Issue by darrenbarklie** [darrenbarklie/maccop#2]
![image](https://user-images.githubusercontent.com/3026261/33142439-6439b0ea-cfae-11e7-8525-c910157af224.png)
1. Missing the `logo-small` asset.
2. Spell "Youtube" with correct capitalization: "YouTube"

**Comment by thanhthao993** [comment]
Updated!

**Comment by darrenbarklie** [comment]
Thanks.
