### ISSUE TITLE
home/come-to-kenya: Responsive Behaviour

### ISSUE THREAD

**Issue by darrenbarklie** [darrenbarklie/maccop#3]
![image](https://user-images.githubusercontent.com/3026261/33152055-8e9a477c-cfd2-11e7-8982-b9f392fe3ae9.png)

Images aren't responsive.

**Comment by thanhthao993** [comment]
Please check it again!

**Comment by darrenbarklie** [comment]
I might still refactor these some more.  They still look stretched at times.  Might have to solve it with a wrapper div.  Reassigning to me.
